var currencyMap = {
  // Countries priced in USD
  'United States': 'USD',
  Argentina: 'USD',
  Afghanistan: 'USD',
  Albania: 'USD',
  Algeria: 'USD',
  Angola: 'USD',
  Anguilla: 'USD',
  'Antigua and Barbuda': 'USD',
  Armenia: 'USD',
  Aruba: 'USD',
  Azerbaijan: 'USD',
  Bahamas: 'USD',
  Bahrain: 'USD',
  Barbados: 'USD',
  Belarus: 'USD',
  Belize: 'USD',
  Benin: 'USD',
  Bermuda: 'USD',
  Bhutan: 'USD',
  Bolivia: 'USD',
  Botswana: 'USD',
  'British Virgin Islands': 'USD',
  Brunei: 'USD',
  'Burkina Faso': 'USD',
  Cambodia: 'USD',
  Cameroon: 'USD',
  'Cape Verde': 'USD',
  'Cayman Islands': 'USD',
  Chad: 'USD',
  Comoros: 'USD',
  'Congo, Democratic Republic of the (Kinshasa)': 'USD',
  'Congo, Republic of the (Brazzaville)': 'USD',
  'Costa Rica': 'USD',
  "Cote D'Ivoire": 'USD',
  Djibouti: 'USD',
  Dominica: 'USD',
  'Dominican Republic': 'USD',
  Ecuador: 'USD',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'USD',
  Eritrea: 'USD',
  Fiji: 'USD',
  Gabon: 'USD',
  Gambia: 'USD',
  Georgia: 'USD',
  Ghana: 'USD',
  Grenada: 'USD',
  Guatemala: 'USD',
  Guinea: 'USD',
  'Guinea-Bissau': 'USD',
  Guyana: 'USD',
  Haiti: 'USD',
  Honduras: 'USD',
  Iraq: 'USD',
  Jamaica: 'USD',
  Jordan: 'USD',
  Kuwait: 'USD',
  Kyrgyzstan: 'USD',
  Laos: 'USD',
  Lebanon: 'USD',
  Liberia: 'USD',
  Libya: 'USD',
  Macau: 'USD',
  Madagascar: 'USD',
  Malawi: 'USD',
  Maldives: 'USD',
  Mali: 'USD',
  Mauritania: 'USD',
  Mauritius: 'USD',
  Micronesia: 'USD',
  Moldova: 'USD',
  Mongolia: 'USD',
  Montserrat: 'USD',
  Morocco: 'USD',
  Mozambique: 'USD',
  Myanmar: 'USD',
  Namibia: 'USD',
  Nauru: 'USD',
  Nepal: 'USD',
  Nicaragua: 'USD',
  Niger: 'USD',
  'North Macedonia': 'USD',
  Oman: 'USD',
  Palau: 'USD',
  Panama: 'USD',
  'Papua New Guinea': 'USD',
  Paraguay: 'USD',
  Peru: 'PEN',
  Qatar: 'USD',
  Rwanda: 'USD',
  Samoa: 'USD',
  'São Tomé and Príncipe': 'USD',
  Senegal: 'USD',
  Seychelles: 'USD',
  'Sierra Leone': 'USD',
  'Solomon Islands': 'USD',
  Somalia: 'USD',
  'Sri Lanka': 'USD',
  'St. Kitts and Nevis': 'USD',
  'St. Lucia': 'USD',
  'St. Vincent and the Grenadines': 'USD',
  Suriname: 'USD',
  Tajikistan: 'USD',
  Tonga: 'USD',
  'Trinidad and Tobago': 'USD',
  Tunisia: 'USD',
  Turkmenistan: 'USD',
  'Turks and Caicos Islands': 'USD',
  Uganda: 'USD',
  Uruguay: 'USD',
  Uzbekistan: 'USD',
  Vanuatu: 'USD',
  Venezuela: 'USD',
  Yemen: 'USD',
  Zambia: 'USD',
  Zimbabwe: 'USD',
  Eswatini: 'USD',

  // Countries priced in EUR
  France: 'EUR',
  Germany: 'EUR',
  Spain: 'EUR',
  Italy: 'EUR',
  Portugal: 'EUR',
  Netherlands: 'EUR',
  Ireland: 'EUR',
  Belgium: 'EUR',
  Finland: 'EUR',
  Greece: 'EUR',
  Austria: 'EUR',
  Lithuania: 'EUR',
  Slovakia: 'EUR',
  Latvia: 'EUR',
  Slovenia: 'EUR',
  Estonia: 'EUR',
  Croatia: 'EUR',
  Luxembourg: 'EUR',
  Malta: 'EUR',
  Cyprus: 'EUR',
  'San Marino': 'EUR',
  Serbia: 'EUR',
  'Vatican City': 'EUR',
  Monaco: 'EUR',
  Kosovo: 'EUR',
  Montenegro: 'EUR',
  'Bosnia and Herzegovina': 'EUR',
  Togo: 'EUR',
  'Central African Republic': 'EUR',

  // Countries priced in GBP
  'United Kingdom': 'GBP',
  Gibraltar: 'GBP',

  // Other countries and their pricing currencies
  Canada: 'CAD',
  Australia: 'AUD',
  'New Zealand': 'NZD',
  Japan: 'JPY',
  Brazil: 'BRL',
  India: 'INR',
  Indonesia: 'IDR',
  'Saudi Arabia': 'SAR',
  Poland: 'PLN',
  Sweden: 'SEK',
  Romania: 'RON',
  'Czech Republic': 'CZK',
  Denmark: 'DKK',
  Hungary: 'HUF',
  Bulgaria: 'BGN',
  Turkey: 'TRY',
  Mexico: 'MXN',
  Thailand: 'THB',
  Philippines: 'PHP',
  'South Africa': 'ZAR',
  'South Korea': 'KRW',
  Egypt: 'EGP',
  Nigeria: 'NGN',
  Malaysia: 'MYR',
  Colombia: 'COP',
  Chile: 'CLP',
  Singapore: 'SGD',
  'United Arab Emirates (UAE)': 'AED',
  Ukraine: 'USD', // Priced in USD according to your table
  Kenya: 'KES',
  Israel: 'ILS',
  Switzerland: 'CHF',
  Liechtenstein: 'CHF',
  Iceland: 'ISK',
  Norway: 'NOK',
  'Hong Kong': 'HKD',
  Pakistan: 'PKR',
  Peru: 'PEN',
  Taiwan: 'TWD',
  Tanzania: 'TZS',
  Vietnam: 'VND',
  Kazakhstan: 'KZT',
  Bangladesh: 'BDT',
  'Sri Lanka': 'USD', // Priced in USD according to your table
  Somolia: 'USD', // Priced in USD according to your table
  Somalia: 'USD', // Priced in USD according to your table
};

// Make currencyMap available globally
window.currencyMap = currencyMap;
